# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a1faf57c3241f0226cb1fc7a45ed52130192361c94817035e0c19d45f17d4223cf2047f39a485ff3a99501abf21dfd4774a45f4701d0858e07c5f586f32f8d4

test:
  secret_key_base: 620f2b6aadefe5f7d6597fb21f06b769bd32fad25591823084d8ea65c2c0307136af2af9356dd5700ab838c60cdc4b2223b84c843ffb47965aa57cf5a69bda53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
